'use client'

import { motion } from 'framer-motion'
import { Lock, Crown, ArrowRight, CheckCircle, Sparkles, Zap, TrendingUp, Users, Star } from 'lucide-react'
import Link from 'next/link'

interface LockedLessonUIProps {
    lessonTitle: string
    courseTitle: string
}

export default function LockedLessonUI({ lessonTitle, courseTitle }: LockedLessonUIProps) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-4xl mx-auto py-12"
        >
            {/* Main Lock Visual */}
            <div className="text-center mb-12">
                <motion.div
                    initial={{ scale: 0.8 }}
                    animate={{ scale: 1 }}
                    transition={{ delay: 0.2, type: "spring" }}
                    className="relative inline-block mb-8"
                >
                    {/* Pulsing Glow */}
                    <div className="absolute inset-0 bg-purple-500/20 rounded-full blur-3xl animate-pulse" />

                    {/* Lock Icon Container */}
                    <div className="relative w-32 h-32 mx-auto bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-xl border border-purple-500/30 rounded-full flex items-center justify-center">
                        <Lock className="w-16 h-16 text-purple-400" />
                        <div className="absolute -top-2 -right-2 w-12 h-12 bg-gradient-to-br from-yellow-400 to-orange-500 rounded-full flex items-center justify-center animate-bounce">
                            <Crown className="w-6 h-6 text-white" />
                        </div>
                    </div>
                </motion.div>

                <motion.h2
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.3 }}
                    className="text-4xl md:text-5xl font-black text-white mb-4"
                >
                    Unlock <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">{lessonTitle}</span>
                </motion.h2>

                <motion.p
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.4 }}
                    className="text-zinc-400 text-lg max-w-2xl mx-auto mb-2"
                >
                    You've completed the free preview! Ready to master the complete {courseTitle}?
                </motion.p>

                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.5 }}
                    className="text-purple-400 text-sm font-medium"
                >
                    Join 10,000+ creators who upgraded their game
                </motion.div>
            </div>

            {/* Value Props - 3 Column Grid */}
            <div className="grid md:grid-cols-3 gap-6 mb-12">
                {[
                    { icon: Sparkles, title: '80+ Premium Lessons', desc: 'Complete mastery in 4 courses', gradient: 'from-purple-500 to-pink-500' },
                    { icon: Zap, title: 'AI-Powered Tools', desc: 'Exclusive hook generators & more', gradient: 'from-blue-500 to-cyan-500' },
                    { icon: TrendingUp, title: 'Proven Systems', desc: '$10M+ generated by students', gradient: 'from-green-500 to-emerald-500' }
                ].map((item, i) => (
                    <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.6 + (i * 0.1) }}
                        className="group relative bg-zinc-900/50 border border-white/10 rounded-2xl p-6 hover:border-purple-500/30 transition-all"
                    >
                        <div className={`absolute inset-0 bg-gradient-to-br ${item.gradient} opacity-0 group-hover:opacity-5 rounded-2xl transition-opacity`} />
                        <div className={`w-12 h-12 mb-4 bg-gradient-to-br ${item.gradient} bg-opacity-10 rounded-xl flex items-center justify-center`}>
                            <item.icon className="w-6 h-6 text-white" />
                        </div>
                        <h3 className="font-bold text-white mb-2">{item.title}</h3>
                        <p className="text-sm text-zinc-500">{item.desc}</p>
                    </motion.div>
                ))}
            </div>

            {/* Social Proof */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.9 }}
                className="bg-gradient-to-br from-zinc-900/80 to-zinc-900/40 border border-white/10 rounded-2xl p-8 mb-8"
            >
                <div className="flex items-center justify-between flex-wrap gap-6">
                    <div className="flex items-center gap-4">
                        <div className="flex -space-x-3">
                            {[1, 2, 3, 4].map((i) => (
                                <div key={i} className="w-12 h-12 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 border-2 border-zinc-900 flex items-center justify-center">
                                    <Users className="w-6 h-6 text-white" />
                                </div>
                            ))}
                        </div>
                        <div>
                            <div className="flex items-center gap-2 mb-1">
                                {[1, 2, 3, 4, 5].map((i) => (
                                    <Star key={i} className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                                ))}
                            </div>
                            <p className="text-sm text-zinc-400">
                                <span className="text-white font-bold">10,000+ creators</span> already inside
                            </p>
                        </div>
                    </div>
                    <div className="text-right">
                        <p className="text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-emerald-400">
                            $10M+
                        </p>
                        <p className="text-sm text-zinc-500">Generated by students</p>
                    </div>
                </div>
            </motion.div>

            {/* What You're Missing - Checklist */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1 }}
                className="bg-zinc-900/30 border border-white/10 rounded-2xl p-8 mb-8"
            >
                <h3 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
                    <CheckCircle className="w-6 h-6 text-purple-400" />
                    What You're Missing in This Lesson:
                </h3>
                <div className="space-y-4">
                    {[
                        'Step-by-step implementation guide',
                        'Exclusive templates & frameworks',
                        'Real case studies & examples',
                        'Downloadable resources & worksheets',
                        'Action items with expert feedback'
                    ].map((item, i) => (
                        <motion.div
                            key={i}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: 1.1 + (i * 0.05) }}
                            className="flex items-center gap-3 text-zinc-300"
                        >
                            <div className="w-6 h-6 rounded-full bg-purple-500/20 border border-purple-500/30 flex items-center justify-center flex-shrink-0">
                                <CheckCircle className="w-4 h-4 text-purple-400" />
                            </div>
                            <span>{item}</span>
                        </motion.div>
                    ))}
                </div>
            </motion.div>

            {/* CTA Buttons */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.3 }}
                className="flex flex-col sm:flex-row gap-4 justify-center"
            >
                <Link href="/redeem" className="flex-1 sm:flex-initial">
                    <motion.button
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        className="w-full group relative px-8 py-5 bg-gradient-to-r from-purple-600 to-pink-600 rounded-xl text-white font-bold text-lg overflow-hidden shadow-2xl"
                    >
                        <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                        <div className="relative flex items-center justify-center gap-3">
                            <Crown className="w-6 h-6" />
                            Unlock Full Access
                            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                        </div>
                        <div className="absolute inset-0 bg-white/20 opacity-0 group-hover:opacity-100 blur-xl transition-opacity" />
                    </motion.button>
                </Link>

                <Link href="/learning" className="flex-1 sm:flex-initial">
                    <motion.button
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        className="w-full px-8 py-5 bg-zinc-900 hover:bg-zinc-800 border border-white/10 hover:border-white/20 rounded-xl text-white font-bold text-lg transition-all"
                    >
                        Back to Dashboard
                    </motion.button>
                </Link>
            </motion.div>

            {/* Trust Badge */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1.5 }}
                className="text-center mt-8 text-sm text-zinc-500"
            >
                <div className="flex items-center justify-center gap-2 mb-2">
                    <CheckCircle className="w-4 h-4 text-green-400" />
                    <span className="text-green-400 font-medium">Lifetime Access</span>
                </div>
                One-time payment • No subscriptions • Instant access
            </motion.div>
        </motion.div>
    )
}
